title: Czyang's Blog
author: Chenzhengyang
lang: zh-CN
timezone: Asia/Shanghai

# 构建设置
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/ruby/

# 网站设置
permalink: /posts/:title/
paginate: 10
paginate_path: /page/:num/ 
