title: My GitHub Pages Site
description: A personal website
lang: zh-CN
timezone: Asia/Shanghai
theme: jekyll-theme-minimal

# 构建设置
build:
  exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/ruby/

# Chirpy 主题设置
author:
  name: Your Name
  email: your-email@example.com
  url: 'https://github.com/your-username'
  avatar: /assets/img/avatar.jpg  # 替换为你的头像路径
  bio: '在这里写一段简短的个人介绍'
  location: Your Location
  social:
    github: your-github-username

# 网站设置
permalink: /posts/:title/
paginate: 10
paginate_path: /page/:num/ 